import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const locales: string[] = ["en", "ru"];

export default function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    if (!locales.includes(locale)) redirect("/");

    return (
        <html lang={locale}>
            <body className={inter.className}>{children}</body>
        </html>
    );
}
